### ISSUE TITLE
How do you "ack" messages?

### ISSUE THREAD

**Issue by bradserbu** [jasonpincin/node-amqp-stream#1]

**Comment by jasonpincin** [comment]
This implementation does not currently support manual `ack`ing of messages. See this line: https://github.com/jasonpincin/node-amqp-stream/blob/master/index.js#L145

It's not passing `{ ack: true }` as a subscribe option, which means all messages will be automatically acked, per the [node-amqp driver subscribe defaults](https://github.com/postwait/node-amqp#queuesubscribeoptions-listener).
